name: matrimonial
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_messaging: ^14.7.9
  firebase_storage: ^11.5.6
  firebase_analytics: ^10.7.4
  logger: ^2.0.2+1
  animated_splash_screen: ^1.3.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.13.6
  random_string: ^2.3.1
  flutter_local_notifications: ^16.2.0
  permission_handler: ^11.1.0
  image_picker: ^1.0.6
  flutter_riverpod: ^2.4.9
  flutter_hooks: ^0.20.4
  hooks_riverpod: ^2.4.9
  geocoding: 
  geolocator:
  email_validator: ^2.1.17
  page_transition: ^2.1.0
  intl:
  uuid: 
  http:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/logo.png
    - assets/images/logowhite.png
    - assets/images/google.png
    - assets/images/skillbasedcourses.png
    - assets/images/featuredcourses.png
    - assets/videos/cat.mp4
    - assets/videos/sigma.mp4
    - assets/images/placeholder_image.png
    - assets/images/shorts.png
    - assets/images/skillBasedCourse.png
    - assets/images/audioBooks.png
    - assets/images/humanRights.png
    - assets/images/classBasedCourse.png




  uses-material-design: true
